- name: configure frontend server
  hosts: frontend
  become: yes
  
  tasks:
  - name: instlling nginx
    ansible.builtin.package:
      name: nginx
      state: present
    
  - name: enabling nginx
    ansible.builtin.service:
      name: nginx
      state: present
      enabled: yes

  - name: remove html direcorty
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: absent
  
  - name: create html direcorty
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: directory

  - name: download the frontend code
    ansible.builtin.get_url:
    url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip
    dest: /tmp/frontend.zip
  
  - name: extract the code
    ansible.builtin.unarchive:
    src: /tmp/frontend.zip
    dest: /usr/share/nginx/html
    remote_src: yes 
  
  - name:  copy expense.conf
    ansible.builtin.copy:
      src: expense.conf
      dest: /etc/nginx/default.d/expense.conf 
  
  - name: Restart NGINX
    ansible.builtin.service:
      name: nginx
      state: restarted
 