- name: configure frontend service
  hosts: frontend
  become: yes
  tasks:
  - name: installing nginx 
    ansible.builtin.package:
      name: nginx
      state: present
  
  - name: Enable and starting Nginx Service
    ansible.builtin.systemd:
      name: nginx
      enabled: yes
      state: started
  
  - name: Remove default Nginx/Apache content
    ansible.builtin.file:
      path: /usr/share/nginx/html  # Change to /var/www/html for Apache
      state: absent

  - name: Create an empty directory to avoid errors
    ansible.builtin.file:
      path: /usr/share/nginx/html  # Change to /var/www/html for Apache
      state: directory
      
  - name: Download a frontend code
    ansible.builtin.get_url:
      url: "https://expense-builds.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip"
      dest: "/tmp/frontend.zip"
  
  - name: Unzip a file
    ansible.builtin.unarchive:
      src: /tmp/frontend.zip  
      dest: /usr/share/nginx/html  
      remote_src: yes 
  
  - name: Copy directory from local to remote
    ansible.builtin.copy:
      src: expense.conf
      dest: /etc/nginx/default.d/expense.conf
  
  - name: Restart Nginx service
    ansible.builtin.systemd:
      name: nginx
      state: restarted