- name: configuring mysql
  hosts: mysql
  become: yes
  vars:
    login_host: "mysql.khanishkcosmetics.store"
    login_password: "ExpenseApp@1"

  tasks:
  - name: installing mysql server
    ansible.builtin.package:
      name: mysql-server
      state: present 
  
  - name: Enable MySQL service
    ansible.builtin.systemd:
      name: mysqld
      enabled: yes

  - name: Start MySQL service
    ansible.builtin.systemd:
      name: mysqld
      state: started 

  - name: setting mysql root password
    community.mysql.mysql_user:
      name: root
      login_host: "{{ login_host }}"
      login_password: "{{ login_password }}"
    ignore_errors: true
    register: mysql_info
  
  - name: printing mysql_info
    ansible.builtin.debug:
      msg: "{{ mysql_info }}"

  - name: setup MySQL root password
    ansible.builtin.command: "mysql_secure_installation --set-root-pass {{ login_password }}"
    when: mysql_info.failed is true

      
